### ISSUE TITLE
Ubuntu 22.04 LTS Live PE在虚拟机环境中存在高CPU占用问题

### ISSUE THREAD

**Issue by xgengit** [ghostplant/ubuntu-pe#38]
系统闲置时Xorg进程 cpu占用率很高
在VMWARE和VIRTUALBOX中都能重现问题，可能不是虚拟机环境导致，还没测试实机环境

**Comment by ghostplant** [comment]
有截图或者相关top信息吗？

**Comment by xgengit** [comment]
试过所有显卡选项，3d开关，切换适配器，改大显存，没有改善
![IMG_1267(20220629-153915)](https://user-images.githubusercontent.com/108328054/176380435-370701a6-8ce0-41c5-a81d-1708afdb87c8.jpg)

**Comment by ghostplant** [comment]
您可以把这个文件删除：/etc/xdg/autostart/caja-home.desktop

**Comment by xgengit** [comment]
可以了，至少cpu占用在可接受范围
