### ISSUE TITLE
请问下要怎么访问smb共享文件夹

### ISSUE THREAD

**Issue by vxbmtu94516** [ghostplant/ubuntu-pe#43]
文件都在nas里 直接访问smb://ip/也不行
![image](https://user-images.githubusercontent.com/89058555/207470804-10615e4b-f932-4677-99d9-56dff09d89ed.png)

**Comment by ghostplant** [comment]
请参见bilibili~

**Comment by ghostplant** [comment]
sudo apt install samba 然后重启一下？
