### ISSUE TITLE
使用安装器本地安装系统，且不用admin作为新用户时，没有sudo权限

### ISSUE THREAD

**Issue by d0ng13** [ghostplant/ubuntu-pe#49]
## 描述

- 使用安装器本地安装系统，且不用 *admin* 作为新用户时，没有 **sudo** 权限
- 测试版本：Ubuntu 24.04 - [noble-mate-x86_64-20240209.iso](https://github.com/ghostplant/ubuntu-pe/releases/download/ubuntu-24.04/noble-mate-x86_64-20240209.iso)
- 建议修正脚本，以支持非 *admin* 名称的新用户具有sudo权限
---
- 安装器脚本 /sbin/ubi-lite 中，**function users** 的 **274** 行附近
   - 使用 adduser 代替 useradd 创建用户，但没有将用户添加至 **sudo group** 
   - 默认新用户名 admin 的 **admin group** 在 /etc/sudoers 里，恰巧不受影响 t.t
- 缓解方案
  - 装完以后先改好 /etc/sudoers ， 或者之后回来改也行

**Comment by ghostplant** [comment]
在 noble-mate-x86_64-20240224.iso 中已经修复该问题，多谢错误汇报！

**Comment by d0ng13** [comment]
更新 *noble-mate-x86_64-20240224.iso* 后安装器工作正常。问题解决，话题结束。
